### ISSUE TITLE
Investigate fuzzy use of nested EXP reactions in CTD

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/ctd-to-biopax#2]
(B. Arman Aksoy created an issue 2014-06-20 in the original gsoc14 Bitbucket project)

For example, not sure what the following means:

```
<ixn id="3404552">
        <taxon id="10090">Mus musculus</taxon>
        <reference pmid="22102721"/>
        <axn code="exp" degreecode="1" position="1" parentid="3404552">affects the expression of</axn>
        <actor type="gene" id="GENE:6624" parentid="3404552" form="mutant form" position="1">FSCN1</actor>
        <actor type="ixn" id="3404553" parentid="3404552" position="2">
                <axn code="exp" degreecode="+" position="1" parentid="3404553">results in increased expression of</axn>
                <actor type="chemical" id="MESH:D013755" parentid="3404553" position="1">Tetradecanoylphorbol Acetate</actor>
                <actor type="gene" id="GENE:7124" parentid="3404553" form="protein" position="2">TNF</actor>
        </actor>
</ixn>
```

**Comment by armish** [comment]
We talked with the CTD people about this issue and they said they are planning to fix this with the upcoming releases; but I really don't think they will be fixing it. When we were talking about this issue with @emekdemir and @ozgunbabur, they suggested using +/- controllers to represent these relationships; but I didn't have a chance to implement that :(

**Comment by IgorRodchenkov** [comment]
I think, in this case, the root code="exp" should be treated as if it were "rxn".
